lane :test do
  swiftlint(
    mode: :lint,
    config_file: ".swiftlint-ci.yml",
    output_file: "swiftlint.result.txt",
    ignore_exit_status: true
  )

  swiftlint_codequality(
    path: 'swiftlint.result.txt',
    output: 'swiftlint.report.txt'
  )
end
